# Generated by Django 5.0.2 on 2024-02-24 09:23

import MyProjectRegularExam.account.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=15, validators=[MyProjectRegularExam.account.models.validate_username, django.core.validators.MinLengthValidator(3)])),
                ('email', models.EmailField(max_length=254)),
                ('age', models.PositiveIntegerField(help_text='Age requirement: 21 years and above.', validators=[django.core.validators.MinValueValidator(21)])),
                ('password', models.CharField(max_length=20)),
                ('first_name', models.CharField(blank=True, max_length=25, null=True)),
                ('last_name', models.CharField(blank=True, max_length=25, null=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
